language: java
jdk: oraclejdk7
before_install:
- chmod +x gradlew
- sudo apt-get update -qq
- sudo apt-get install -qq libstdc++6:i386 lib32z1 expect
- export COMPONENTS=build-tools-19.0.3,android-18,sysimg-18,extra-android-support,extra-android-m2repository
- curl -L https://raw.github.com/embarkmobile/android-sdk-installer/master/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS
- source ~/.android-sdk-installer/env
- export TERM=dumb
script: ./gradlew assembleDebug

